name: CD

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
      environment:
        required: false
        type: string
    secrets:
      envPAT:
        required: true

jobs:
  CD:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Show information
        run: |
          echo ${{ inputs.config-path }}
          echo ${{ secrets.envPAT}}

      - name: Determine Environment
        id: extract_environment
        run: |
          starts_with_qa=$(startsWith(${{github.ref}}, 'refs/tags/qa'))
          echo "Ref starts with 'refs/tags/qa': $starts_with_qa"


      # with:
      #   repo-token: ${{ secrets.envPAT }}
      #   configuration-path: ${{ inputs.config-path }}
