name: CD

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
      deploy_env:
        required: false
        type: string
    secrets:
      envPAT:
        required: true

jobs:
  CD:
    runs-on: ubuntu-latest
    environment: production

    steps:
  
      - name: Show information
        run: |
          echo ${{ inputs.config-path }}
          echo ${{ secrets.envPAT}}
          echo ${{ inputs.deploy_env }}
 


      # with:
      #   repo-token: ${{ secrets.envPAT }}
      #   configuration-path: ${{ inputs.config-path }}
