name: CD

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
      environment:
        required: false
        type: string
    secrets:
      envPAT:
        required: true

jobs:
  CD:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Run Script
        id: script
        run: |
          tag=process.env.GITHUB_REF
          echo "result=$tag" >> $GITHUB_OUTPUT


      - name: Print Result
        run: |
          result_value=${{ steps.script.outputs.result }}
          echo "Result:$result_value"

      - name: Show information
        run: |
          echo ${{ inputs.config-path }}
          echo ${{ secrets.envPAT}}
          echo ${{ steps.tagName.outputs.tag }}
 


      # with:
      #   repo-token: ${{ secrets.envPAT }}
      #   configuration-path: ${{ inputs.config-path }}
