name: CD

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
      environment:
        required: false
        type: string
    secrets:
      envPAT:
        required: true

jobs:
  CD:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Run Script
        id: script
        run: |
          tag=$(echo "${{ github.ref }}" | awk -F"-" '{print $NF}')
          echo "result=$tag" >> $GITHUB_ENV

      - name: Print Result
        run: |
          result_value=${{ env.result }}
          echo "Result: $result_value"

      - name: Show information
        run: |
          echo ${{ inputs.config-path }}
          echo ${{ secrets.envPAT}}
          echo ${{ steps.tagName.outputs.tag }}
 


      # with:
      #   repo-token: ${{ secrets.envPAT }}
      #   configuration-path: ${{ inputs.config-path }}
