name: CD

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
      environment:
        required: false
        type: string
    secrets:
      envPAT:
        required: true

jobs:
  CD:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Show information
        run: |
          echo ${{ inputs.config-path }}
          echo ${{ secrets.envPAT}}

      - name: Determine Environment
        id: extract_environment
        run: |
          TAG_NAME="${{ inputs.environment }}"
          ENVIRONMENT="${TAG_NAME##*-}"
          echo "::set-output name=environment::${ENVIRONMENT}"

      # with:
      #   repo-token: ${{ secrets.envPAT }}
      #   configuration-path: ${{ inputs.config-path }}
