name: CD

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
      environment:
        required: false
        type: string
    secrets:
      envPAT:
        required: true

jobs:
  CD:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Run Script
        id: script
        run: |
          echo "name=result::$(node -e 'const cadena = process.env.GITHUB_REF; console.log(cadena.substring(7, 9));')" >> $GITHUB_OUTPUT

      - name: Set output
        run: echo "::set-output name={name}::{value}"

      - name: Set output
        run: echo "{name}={value}" >> $GITHUB_OUTPUT

      - name: Save state
        run: echo "::save-state name={name}::{value}"

      - name: Print Result
        run: |
          result_value=${{ steps.script.outputs.result }}
          echo "Result: $result_value"

      - name: Show information
        run: |
          echo ${{ inputs.config-path }}
          echo ${{ secrets.envPAT}}
          echo ${{ steps.tagName.outputs.tag }}
 


      # with:
      #   repo-token: ${{ secrets.envPAT }}
      #   configuration-path: ${{ inputs.config-path }}
