name: Coverage

on: 
  pull_request:
    branches:
      - master 

jobs:
  Test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [20]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.version }}
        uses: actions/setup-node@v4       
        with:
          node-version: ${{ matrix.version }}
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run build
        run: npm run build
      
      - name: Run tests
        run: npm run test
      
      - name: Coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
           github-token: ${{ secrets.SECRET_TOKEN }}
           test-script: npm test
